name: Build and Release Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-release-builds
          path: |
            release-builds/*.zip
            release-builds/*.dmg
            release-builds/*.deb
            release-builds/*.rpm
            release-builds/*.AppImage
            release-builds/*.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-release-builds
          path: release-builds/ubuntu

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-release-builds
          path: release-builds/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-release-builds
          path: release-builds/macos

      - name: Rename Linux artifacts
        run: |
          for file in release-builds/ubuntu/*; do
            dirname=$(dirname "$file")
            filename=$(basename "$file")
            mv "$file" "$dirname/linux_$filename"
          done

      - name: Create a release tag
        id: create_tag
        run: |
          TAG_NAME=v${{ github.run_number }}
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-builds/ubuntu/linux_*.zip
            release-builds/ubuntu/linux_*.AppImage
            release-builds/ubuntu/linux_*.deb
            release-builds/ubuntu/linux_*.rpm
            release-builds/windows/*.exe
            release-builds/windows/*.zip
            release-builds/macos/*.dmg
            release-builds/macos/*.zip
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
